---
- name: apt | install packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-dev
    - python-pip
    - python-setuptools
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
  tags:
    - python

- name: pip | install packages
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ item }}"
  with_items: python_packages
  when: python_packages
  tags:
    - python
