---
- name: apt | install legacy python packages
  apt:
    name:
    - python
    - python-dev
    - python-pip
    state: latest
  when: python_legacy_support

- name: apt | install python packages
  apt:
    name:
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python-setuptools # Needed to run the pip task
    state: latest

- name: pip | install packages
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ python_packages }}"
