---
- name: apt | install python packages
  apt:
    name: "{{ python_apt_packages }}"
    state: latest

- name: pip | install packages
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ python_packages }}"
