---
- name: apt | install python packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-dev
    - python3
    - python3-dev
  tags:
    - python

- name: pip | check
  stat:
    path: "{{ python_pip_executable }}"
  register: pip
  tags:
    - python

- name: pip | fetch
  get_url:
    url: "{{ python_pip_download_url }}"
    dest: /tmp/get-pip.py
    mode: 0755
    force: yes
  when: not pip.stat.exists
  tags:
    - python

- name: pip | install
  shell: /tmp/get-pip.py
  when: not pip.stat.exists
  tags:
    - python

- name: pip | update
  shell: "{{ python_pip_executable }} install -U pip"
  when: pip.stat.exists
  tags:
    - python

- name: pip | install packages
  pip:
    executable: "{{ python_pip_executable }}"
    state: latest
    name: "{{ item }}"
  with_items: python_packages
  when: python_packages
  tags:
    - python
